CREATE TABLE section
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	fid INT UNSIGNED NOT NULL,
	ancient INT UNSIGNED NOT NULL,
	article INT UNSIGNED NOT NULL,
	leaf TINYINT NOT NULL DEFAULT 1,
	PRIMARY KEY (id)

) 
;


